In [1]:
import numpy as np

In [4]:
one= np.array([[1,2],[3,4]])
two= np.array([[5,6],[7,8]])

oneT=one.T
#z=np.matmul(oneT,two)
z=oneT@two
print(z)

[[26 30]
 [38 44]]


In [5]:
# Checking somethign
a = np.array([1,2,3,4]).reshape(-1,1)
b = np.array([1,2,3]).reshape(1,-1)
print(a)
print(b)
print(f"(a + b).shape: {(a + b).shape}, \na + b = \n{a + b}")

[[1]
 [2]
 [3]
 [4]]
[[1 2 3]]
(a + b).shape: (4, 3), 
a + b = 
[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]
